# Generated by Django 3.2.6 on 2023-03-24 02:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.BigIntegerField()),
                ('searched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_time', models.BigIntegerField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_query', to='report.query')),
            ],
            options={
                'ordering': ('-searched_at',),
            },
        ),
    ]
